### ISSUE TITLE
ДЗ 13

### ISSUE THREAD

**Issue by AndyAnderyan** [sveka0/homework#14]
### **Завдання 2, пункт 9**
9. Визначте обробку події фокус для селектора .login-form input, що змінює колір рамки на значення --active-color

![0054](https://github.com/sveka0/homework/assets/70598450/d9eaaafc-3f9f-4f0c-b3de-969186ea4c10)

Це правило треба записати в окремому селекторі:
```css
.login-form input:focus {
   border-color: var(--active-color);
}
```
### **Завдання 1, та всі інші пункти 2-го завдання виконані на 100%! Гарна робота!**
