### ISSUE TITLE
ДЗ 6

### ISSUE THREAD

**Issue by AndyAnderyan** [sveka0/homework#7]
### **Завдання 7**
![image](https://github.com/sveka0/homework/assets/70598450/b13931a0-0bd4-43ea-81d3-e499481b7379)

**Це все можна було записати так:**
```
- Встановіть елементу li помаранчевий колір, якщо він не має аргумента class="first-item"
```
**Рішення:**
```css
li:not(.first-item) {   
	color: orange; 
}
```
```
- Встановіть всім елементаи li чорний текст і жовтий фон, крім елемента li з класом .first-item та останнього елемента li у списку
```
**Рішення:**
```css
li:not(.first-item):not(:last-of-type) {
   background: yellow;
   color: black;
}
```
